# Generated by Django 5.2.3 on 2025-07-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="equipment_id",
            field=models.CharField(default="EQP-0001", max_length=20),
        ),
    ]
