# Generated by Django 5.2.3 on 2025-07-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_api", "0002_alter_equipment_equipment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="member_id",
            field=models.CharField(default="MEM-0001", max_length=20),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="plan_id",
            field=models.CharField(default="PLN-0001", max_length=20),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="trainer_id",
            field=models.CharField(default="TRN-0001", max_length=20),
        ),
    ]
