# Generated by Django 5.2.3 on 2025-07-02 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_api", "0003_alter_member_member_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershippayment",
            name="payment_id",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["gym_owner", "date"], name="gym_api_att_gym_own_dfdb67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["gym_owner", "check_in_time"],
                name="gym_api_att_gym_own_9eda64_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["member", "date"], name="gym_api_att_member__4bfd9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["date", "check_in_time"], name="gym_api_att_date_e4de27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["attendance_id"], name="gym_api_att_attenda_c9ca4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["gym_owner", "is_working"],
                name="gym_api_equ_gym_own_6625ca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["gym_owner", "equipment_type"],
                name="gym_api_equ_gym_own_357a4c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["gym_owner", "next_maintenance_date"],
                name="gym_api_equ_gym_own_240396_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["equipment_id"], name="gym_api_equ_equipme_8e7ba7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["gym_owner", "is_active"], name="gym_api_mem_gym_own_6a69bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["gym_owner", "membership_expiry"],
                name="gym_api_mem_gym_own_3e778d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["gym_owner", "join_date"], name="gym_api_mem_gym_own_585c2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["member_id"], name="gym_api_mem_member__6ebc8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["user"], name="gym_api_mem_user_id_c0f428_idx"),
        ),
        migrations.AddIndex(
            model_name="membershippayment",
            index=models.Index(
                fields=["gym_owner", "payment_date"],
                name="gym_api_mem_gym_own_300d34_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="membershippayment",
            index=models.Index(
                fields=["gym_owner", "status"], name="gym_api_mem_gym_own_25259a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membershippayment",
            index=models.Index(
                fields=["gym_owner", "member"], name="gym_api_mem_gym_own_255279_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membershippayment",
            index=models.Index(
                fields=["payment_id"], name="gym_api_mem_payment_0ab8cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membershippayment",
            index=models.Index(
                fields=["member", "payment_date"], name="gym_api_mem_member__03e4bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionplan",
            index=models.Index(
                fields=["gym_owner", "is_active"], name="gym_api_sub_gym_own_62ca69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionplan",
            index=models.Index(
                fields=["gym_owner", "price"], name="gym_api_sub_gym_own_5812b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionplan",
            index=models.Index(
                fields=["plan_id"], name="gym_api_sub_plan_id_06041e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainer",
            index=models.Index(
                fields=["gym_owner", "is_available"],
                name="gym_api_tra_gym_own_b213c3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trainer",
            index=models.Index(
                fields=["gym_owner", "specialization"],
                name="gym_api_tra_gym_own_f3d835_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trainer",
            index=models.Index(
                fields=["trainer_id"], name="gym_api_tra_trainer_fc4f73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainer",
            index=models.Index(fields=["user"], name="gym_api_tra_user_id_fdc785_idx"),
        ),
    ]
