# Generated by Django 5.2.3 on 2025-07-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gym_api",
            "0005_alter_equipment_equipment_id_alter_member_member_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="attendance_id",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="plan_id",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
