# Generated by Django 5.2.3 on 2025-07-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_api", "0006_alter_attendance_attendance_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gymowner",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="gym_owner_profiles/"
            ),
        ),
    ]
