# Generated by Django 5.2.3 on 2025-07-03 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_api", "0008_alter_membershippayment_payment_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainerMemberAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gym_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_member_associations",
                        to="gym_api.gymowner",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_associations",
                        to="gym_api.member",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_associations",
                        to="gym_api.trainer",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["gym_owner", "trainer", "is_active"],
                        name="gym_api_tra_gym_own_eb20c2_idx",
                    ),
                    models.Index(
                        fields=["gym_owner", "member", "is_active"],
                        name="gym_api_tra_gym_own_12ae88_idx",
                    ),
                    models.Index(
                        fields=["assigned_date"], name="gym_api_tra_assigne_ead3f7_idx"
                    ),
                ],
                "unique_together": {("gym_owner", "trainer", "member")},
            },
        ),
    ]
