# Generated by Django 4.2.23 on 2025-07-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_api', '0009_add_trainer_member_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymowner',
            name='profile_picture_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded profile picture for Railway deployment', null=True),
        ),
        migrations.AddField(
            model_name='gymowner',
            name='profile_picture_content_type',
            field=models.CharField(blank=True, help_text='Content type of the base64 image', max_length=50, null=True),
        ),
    ]
