# Generated by Django 4.2.23 on 2025-07-10 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_api', '0010_gymowner_profile_picture_base64_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('member_expiry', 'Member Expiry'), ('member_expiring_soon', 'Member Expiring Soon'), ('payment_received', 'Payment Received'), ('system_alert', 'System Alert')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('gym_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='gym_api.gymowner')),
                ('related_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym_api.member')),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym_api.membershippayment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gym_owner', 'is_read'], name='gym_api_not_gym_own_675fbc_idx'), models.Index(fields=['gym_owner', 'type'], name='gym_api_not_gym_own_7b8656_idx'), models.Index(fields=['created_at'], name='gym_api_not_created_75c90c_idx')],
            },
        ),
    ]
