name: gym_management
description: A comprehensive gym management application with member tracking, trainer management, equipment monitoring, and attendance system.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies only
  http: ^1.2.0
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  
  # Authentication & Security
  flutter_secure_storage: ^9.2.2
  crypto: ^3.0.5
  
  # Permissions
  permission_handler: ^11.3.1
  
  # File handling
  path_provider: ^2.1.3
  
  # Image handling
  image_picker: ^1.0.7
  
  # QR Code scanning (mobile only) - temporarily disabled for iOS build compatibility
  # mobile_scanner: ^5.0.0
  
  # Google Sign-In
  google_sign_in: ^6.2.1
  
  # URL launcher for phone, email, WhatsApp
  url_launcher: ^6.2.5
  
  # Sharing functionality
  share_plus: ^9.0.0
  
  # Web QR Code alternative
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/